#ifndef INDUCONTROLCORE_GLOBAL_H
#define INDUCONTROLCORE_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(INDUCONTROLCORE_LIBRARY)
#  define INDUCONTROLCORE_EXPORT Q_DECL_EXPORT
#else
#  define INDUCONTROLCORE_EXPORT Q_DECL_IMPORT
#endif

#endif // INDUCONTROLCORE_GLOBAL_H
